#### Definiendo la libreria numpy

In [3]:
import numpy as np

#### Lista de 10 elementos

In [4]:
lista = list(range(1,11))
lista


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformando la lista a un Array

In [5]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Corroborando el tipo de objeto

In [6]:
type(arreglo)

numpy.ndarray

#### Corroborando el tipo de datos de arreglo

In [7]:
arreglo.dtype

dtype('int32')

#### Definiendo el Array de int32 a float32

In [8]:
np.array(arreglo, dtype = np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### Sigue siendo un array de int32

In [9]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformando los datos de int32 a float32

In [10]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### Funcion similar a range pero ocupando arrays

In [11]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Arreglo de 2 en 2 utilizando a range

In [12]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h1>Algunas funciones de numpy<h1>
<h1 style = "color:red"><b>Algunas funciones de numpy</b></h1>

#### Obteniendo la mediana del array

In [13]:
promedio = np.mean(arreglo)
promedio

5.5

#### Obteniendo el promedio del array

In [14]:
promedio = np.median(arreglo)
promedio

5.5

#### Desviacion estandar del arreglo

In [15]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

#### Generacion de un arreglo de 10 elementos de solo unos

In [16]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Generacion de arreglos de ceros 

In [17]:
arreglos_ceros = np.zeros(5)
arreglos_ceros

array([0., 0., 0., 0., 0.])

#### Transformando el arreglo de unos de punto flotante a enteros

In [18]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h1 style = "color:blue"><b>Utilizando la funcion random</b></h1>

#### Generando arreglos aleatorios de 5 elementos

In [19]:
arreglo_aleatorio = np.random.rand(10)
arreglo_aleatorio

array([0.626821  , 0.83558973, 0.80658528, 0.85630561, 0.65005524,
       0.47146109, 0.14283327, 0.97777515, 0.72642311, 0.36970098])

#### Generar 3 matrizes aleatorias de 3x3

In [20]:
matriz = np.random.rand(3,3)
matriz

array([[0.97714664, 0.81743173, 0.29684812],
       [0.81438699, 0.99296497, 0.61246153],
       [0.24523497, 0.6661951 , 0.06650567]])

#### Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5

In [29]:
arreglo_aleatorio2 = np.random.randint(1,100,5)
arreglo_aleatorio2

array([94, 86, 58, 67, 52])

#### Generar una matriz aleatorias del 1 al 100

In [ ]:
matriz2 = np.random.randint(1,100,(10,10))
matriz2

array([[30, 76, 41, 81, 94, 55, 51, 29, 84, 50],
       [ 2, 70, 48, 85, 64, 30, 97, 28, 28, 64],
       [64, 78, 73, 11, 60, 33, 59, 99, 73, 64],
       [98, 73, 27, 18, 61, 81, 80, 73, 41, 91],
       [64, 30,  1, 74, 11, 66,  6, 13, 67, 94],
       [69, 57, 25,  2, 38, 55,  7, 50, 28, 65],
       [83, 53, 82, 38, 20, 99, 71, 50, 12, 72],
       [91, 19, 74, 30,  1, 70, 48,  8, 92, 34],
       [94, 85,  7, 18, 53, 57, 45, 91, 90, 12],
       [13, 89, 11, 26, 96, 53, 34, 68, 32, 23]])