#### Definiendo la libreria numpy

In [3]:
import numpy as np

#### Lista de 10 elementos

In [6]:
lista = list(range(1,11))
lista


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformando la lista a un Array

In [8]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Corroborando el tipo de objeto

In [9]:
type(arreglo)

numpy.ndarray

#### Corroborando el tipo de datos de arreglo

In [10]:
arreglo.dtype

dtype('int32')

#### Definiendo el Array de int32 a float32

In [11]:
np.array(arreglo, dtype = np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### Sigue siendo un array de int32

In [12]:
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

#### Transformando los datos de int32 a float32

In [13]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

#### Obteniendo el promedio del array

In [15]:
promedio = np.mean(arreglo)
promedio

5.5

#### Obteniendo la mediana del array

In [14]:
mediana = np.mean(arreglo)
mediana

5.5

#### Desviacion estandar del arreglo

In [16]:
desviacion_std = np.std(arreglo)

#### Funcion similar a range pero ocupando arrays

In [5]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Arreglo de 2 en 2 utilizando a range

In [4]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h1>Algunas funciones de numpy<h1>
<h1 style = "color:red"><b>Algunas funciones de numpy</b></h1>