#### Dimensiones

In [1]:
import numpy as np  

#### Generando un arreglo de 12 elementos enteros con random

In [2]:
arreglo = np.random.randint(1,10,12)
arreglo

array([1, 2, 2, 8, 6, 9, 9, 7, 8, 1, 9, 7])

#### Obtener la dimension de un arreglo

In [3]:
np.shape(arreglo)

(12,)

#### transformacion del vector de 12 elementos a matriz 4x3 con reshape

In [4]:
matriz = arreglo.reshape(4,3)
matriz

array([[1, 2, 2],
       [8, 6, 9],
       [9, 7, 8],
       [1, 9, 7]])

#### Transformacion del vector de 12 elementos a matriz 4x3 con reshape

In [5]:
np.shape(matriz)

(4, 3)

#### Otra Transformación del vector de 9 elementos a Matriz 3x4 con Reshape

In [6]:
matriz = arreglo.reshape(3,4)
matriz

array([[1, 2, 2, 8],
       [6, 9, 9, 7],
       [8, 1, 9, 7]])

#### Creando un tensor

In [7]:
t = [[[[1,2,3],[4,5,6],[7,8,9],[1,2,3]]]]
t

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3]]]]